spring:
  application:
    name: bankhelp
  datasource:
    url: jdbc:postgresql://localhost:5432/bankhelp
    username: bankhelp
    password: bankhelp123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.access: DEBUG
security:
  jwt:
    secret: "07UyvNjm5zOf20iGc0tzoBr1hWVtTNjQkJ0tQYDke7s"
    expiration: 900000 # 15 minutos en milisegundos
  refresh-token:
    expiration-days: 7 # 7 d√≠as		