spring:
  application:
    name: bankhelp
  datasource:
    url: jdbc:postgresql://localhost:5432/bankhelp
    username: bankhelp
    password: bankhelp123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.access: DEBUG